import { Report } from '../models/types';
import { INITIAL_REPORTS } from '../data/mockData';

export interface ReportServiceInterface {
  getReports(): Promise<Report[]>;
  getReportById(id: string): Promise<Report | null>;
  createReport(data: Partial<Report>): Promise<Report>;
}

export class MockReportService implements ReportServiceInterface {
  private reports: Report[] = [...INITIAL_REPORTS];

  async getReports(): Promise<Report[]> {
    return new Promise((resolve) => setTimeout(() => resolve([...this.reports]), 100));
  }

  async getReportById(id: string): Promise<Report | null> {
    const r = this.reports.find((item) => item.id === id);
    return r ? { ...r } : null;
  }

  async createReport(data: Partial<Report>): Promise<Report> {
    const newReport: Report = {
      id: `RPT-${String(this.reports.length + 1).padStart(3, '0')}`,
      scanId: data.scanId || 'SCAN-001',
      title: data.title || 'Marine Anomaly Inspection Dossier',
      surveyName: data.surveyName || 'MoES/NIOT Sonar Survey',
      organization: 'Ministry of Earth Sciences (MoES)',
      department: 'National Institute of Ocean Technology (NIOT)',
      generatedAt: new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC',
      generatedBy: data.generatedBy || 'Dr. R. Ramanathan',
      detectionCount: data.detectionCount || 0,
      highPriorityCount: data.highPriorityCount || 0,
      verifiedCount: data.verifiedCount || 0,
      rejectedCount: data.rejectedCount || 0,
      pendingCount: data.pendingCount || 0,
      status: 'READY',
      executiveSummary: data.executiveSummary || 'Automated anomaly assessment generated by NEZA AI platform.',
      targetDetections: data.targetDetections || [],
    };

    this.reports.unshift(newReport);
    return newReport;
  }
}

export const reportService = new MockReportService();
